#!/usr/bin/env bash
set -x

BASEDIR="$(dirname -- "${BASH_SOURCE[0]}")"
cd "$BASEDIR" || return

rm -fr 'data/config'
cp -r 'data/config.template' 'data/config'
./src/setup.sh 'data/config' 'data/static'
daemon -f -p data/run.pid -o log ./src/server.sh 'data/config'
while ! curl -v localhost; do sleep 1; done
