#!/bin/sh

# PROVIDE: ftp_watchd
# REQUIRE: NETWORKING SERVERS
# BEFORE: DAEMON
# KEYWORD: shutdown

# Add the following lines to /etc/rc.conf to enable ftp_watchd:
#
# ftp_watchd_enable="yes"
# ftp_watchd_script="/full/path/to/upload_script"

. /etc/rc.subr

name=ftp_watchd
rcvar=ftp_watchd_enable

load_rc_config $name

# uploadscript
command=/usr/local/sbin/pure-uploadscript
pidfile=${pidfile:-"/var/run/pure-uploadscript.pid"}
ftp_watchd_enable=${ftp_watchd_enable:-"no"}
ftp_watchd_script=${ftp_watchd_script:-"/usr/local/sbin/ftp_watchd"}
# command_args
command_args="-B -p ${pidfile} -r ${ftp_watchd_script}"

start_cmd="${name}_start"
stop_cmd="${name}_stop"

ftp_watchd_start() {
  echo "Starting ${command}."
  ${command} ${command_args}  
}

ftp_watchd_stop() {
  pid=$(check_pidfile ${pidfile} ${command})
  if [ -z ${pid} ]; then
    echo "Upload script not running? (check ${pidfile})."
    return 1
  fi
  echo "Stopping ${command}."
  kill -${sig_stop:-TERM} ${pid}
  [ $? -ne 0 ] && [ -z "$rc_force" ] && return 1
  wait_for_pids ${pid}
}

run_rc_command "$1"
